<a href="https://colab.research.google.com/github/MarcosGutierrez97/03MIAR-Algoritmos-de-optimizaci-n/blob/main/SEMINARIO/Seminario_MarcosAGutierrez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Marcos Gutierrez  <br>
Url: <br>
Problema:
> 1. Sesiones de doblaje(Este seleccioné) <br>
>2. Organizar los horarios de partidos de La Liga<br>


Descripción del problema:(copiar enunciado)

....

(*) La respuesta es obligatoria

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.

Respuesta

In [3]:
from math import factorial
total_tomas = 30
num_posibilidades = factorial(total_tomas)
print("El numero de posibles combinaciones sin restricciones es: " + str(num_posibilidades))

El numero de posibles combinaciones sin restricciones es: 265252859812191058636308480000000

La unica restriccion es que el numero maximo de tomas por día sea 6. Se vería de la siguiente forma:
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky"> Dias </th>
    <th class="tg-0pky">1er</th>
    <th class="tg-0pky">2do</th>
    <th class="tg-0pky">3er</th>
    <th class="tg-0pky">4to</th>
    <th class="tg-0pky">5to</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">Tomas Totales</td>
    <td class="tg-0pky">30</td>
    <td class="tg-0pky">24</td>
    <td class="tg-0pky">18</td>
    <td class="tg-0pky">12</td>
    <td class="tg-0pky">6</td>
  </tr>
  <tr>
    <td class="tg-0pky">Max Tomas dia</td>
    <td class="tg-0pky">6</td>
    <td class="tg-0pky">6</td>
    <td class="tg-0pky">6</td>
    <td class="tg-0pky">6</td>
    <td class="tg-0pky">6</td>
  </tr>
</tbody>

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)

Respuesta:

Un dataframe de pandas-que vendrian siendo un arrelgo de elementos serie-es el que creo que mas se ajusta dada la estructura de la informacion y de los datos.

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

**Respuesta**

1. Funcion objetivo:
##### Definición del Modelo:
- Sea A el conjunto de actores, con índice $a∈A$
- Sea S el conjunto de sesiones de grabación, con índice $s∈S$
- Sea T el conjunto de tomas de grabación, con índice $t∈T$
- Sea ns el número máximo de tomas permitidos en la sesión de grabación s, con
$ns∈N$. Para el modelo original tomaremos que todas las convocatorias tienen el
mismo número de tomas máximo igual a 6
- Sea M es el número máximo de sesiones de grabación en las que un take puede
ser dividido, con $M∈N$


Definidas estas variables, **función objetivo sería el siguiente:**
min z = $\sum_{a∈A}\sum_{s∈S}(Xas)$

El problema es uno de **minimización** ya que se busca minizimar el costo en la grabación de tomas.

In [4]:
#Librerias necesarias
import numpy as np
import pandas as pd
import seaborn as sns
import os
import matplotlib.pyplot as plt
import random
import warnings
import copy
import time
import collections
import operator
from datetime import datetime
from pandas import Series, DataFrame
from seaborn import load_dataset

In [30]:
# Cargar en un Dataframe los datos del Excel
df  = pd.read_excel('/content/Datos problema doblaje(30 tomas, 10 actores).xlsx', header=None, skiprows=1)
df.pop(11)

#Convertir Dataframe a un array
df = np.array(df)

# # Limpiar Dataframe eliminando las filas y columnas innecesarias
df = pd.DataFrame(df, columns=['Toma','1','2','3','4','5','6','7','8','9','10','Total'])
df= df.drop(0,0)
df= df.drop(31,0)
df= df.drop(32,0)
df= df.drop(['Toma'],1)
df= df.drop(['Total'],1)
df.index.name='Tomas por Actores'
display(df)

<ipython-input-30-b009324cd824>:10: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df= df.drop(0,0)
<ipython-input-30-b009324cd824>:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df= df.drop(31,0)
<ipython-input-30-b009324cd824>:12: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df= df.drop(32,0)
<ipython-input-30-b009324cd824>:13: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df= df.drop(['Toma'],1)
<ipython-input-30-b009324cd824>:14: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df= df.drop(['Total'],1)

                     1    2    3    4    5    6    7    8    9   10
Tomas por Actores
1                  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
2                  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
3                  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
4                  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
5                  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6                  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
7                  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
8                  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
9                  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
10                 1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
11                 1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
12                 1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0
13                 1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
14                 1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
15                 1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
16                 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
17                 1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
18                 0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
19                 1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
20                 1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
21                 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
22                 1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
23                 1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
24                 0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
25                 1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
26                 1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
27                 0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
28                 1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
29                 1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
30                 1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0

Diseña un algoritmo para resolver el problema por fuerza bruta

In [31]:
# Definir Arreglo de Actores y total_actores, diccionario de solución mínima y costmin
actores = [1,2,3,4,5,6,7,8,9,10]
total_actores = [0]
costmin = 1000
solucion_min = {}

In [35]:
#Funciones necesarias
def min_actores(dias, datos_tomas):
    contador=0
    rmax=0
    for x in datos_tomas.index-1:
        if x+1 not in dias:
            y=datos_tomas.iloc[x]
            contar=np.array(collections.Counter(y)[1])
        if contar < contador:
            rmin=x
            contador=contar
    return (rmin, contador)

def max_actores(dias, datos_tomas):
    contador=0
    rmax=0
    for x in datos_tomas.index-1:
        if x+1 not in dia:
            y=datos_tomas.iloc[x]
            contar=np.array(collections.Counter(y)[1])
        if contar > contador:
            rmax=x
            contador=contar
    return (rmax, contador)

def tomas_aleatoria(dias, datos_tomas):
    y=1
    while y==1:
        ran=random.randint(1,30)
        y = y + 1
        if ran not in dias:
            break
    return ran-1, 0

def serie_tomas1(rmax,datos_tomas,dias):
    actores=[1,2,3,4,5,6,7,8,9,10]
    series={}
    contar=0
    for x in datos_tomas.index-1:
        sa=actores*datos_tomas.iloc[rmax]
        sa=np.array(list(sa))
        sa=set(sa)
        if x is not rmax and x+1 not in dias:
            sg=actores*datos_tomas.iloc[x]
            sg=np.array(list(sg))
            sg=set(sg)
            cruce=len(sa&sg)
            series.setdefault(x+1,cruce)
    ordenarseries = dict(sorted(series.items(),key=operator.itemgetter(1), reverse=True))
    return ordenarseries

def serie_tomas2(rmax,datos_tomas,dias):
    actores=[1,2,3,4,5,6,7,8,9,10]
    series={}
    contar=0
    for x in datos_tomas.index-1:
        sa=actores*datos_tomas.iloc[rmax]
        sa=np.array(list(sa))
        sa=set(sa)
        if x is not rmax and x+1 not in dias:
            sg=actores*datos_tomas.iloc[x]
            sg=np.array(list(sg))
            sg=set(sg)
            cruce=len(sa&sg)
            contarsg=np.array(collections.Counter(sg)[1])
            contarsa=np.array(collections.Counter(sa)[1])
            cruce=cruce+(contarsa-contarsg)**2
            series.setdefault(x+1,cruce)
    ordenarseries = dict(sorted(series.items(),key=operator.itemgetter(1), reverse=True))
    return ordenarseries

def organizar_agenda(cruce,dia):
        contador=0
        for y in cruce:
            contador=contador+1
            if contador < 6:
                dia.append(y)
        return dia

Respuesta

In [32]:
# Por fuerza bruta
# Iterar por 10000 para buscar el menor costo
# Se generan combinaciones aleatorias y se evalua su eficiencia

def aleatorio(f):
    no_avaliable = []
    solucion = {}
    for i in range(5):
        cont = 0
        y = []
        while True:
            x = random.randint(1,30)
            if x not in no_avaliable:
                   no_avaliable.append(x)
                   cont = cont +1
                   y.append(x)
                   solucion.setdefault(i+1,y)
            if cont > 5:
                    break
    return solucion

for p in range(10000):
    cost = 0
    solucion2 = []
    solucion2 = aleatorio(0)
    #flag = False
    #print(solucion2)
    for key in solucion2:
        for toma in range(6):
            valor = solucion2[key][toma]
            take = df.iloc[valor-1]
            take=np.array(list(take))
            total_actores=np.array(list(total_actores))
            #print(take)
            set1 = (take * actores)
            set1=set(set1)
            #print(set1)
            #print(total_actores)
            total_actores = set(total_actores)
            total_actores = set1|total_actores

        cost = cost + len(total_actores)

        total_actores = [0]
    #Encontrar el costo mínimo y la solucion guardarlo
    if cost < costmin:
        costmin= cost
        solucion_min = solucion2
    #print('Valor Costo = ',cost)

#Imprimir el costo mínimo y la solucion donde está el costo mínimo
print('* Costo Minimo: ', costmin)
print('* Solucion Minima', solucion_min)

* Costo Minimo:  38
* Solucion Minima {1: [16, 25, 6, 2, 23, 26], 2: [20, 9, 22, 17, 1, 27], 3: [13, 30, 28, 4, 5, 7], 4: [8, 29, 12, 10, 3, 24], 5: [18, 19, 11, 21, 15, 14]}

Calcula la complejidad del algoritmo por fuerza bruta:

**Complejidad**: de orden n**2

Respuesta

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

In [36]:
#Algoritmo mejorado
def algoritmo_mejorado(rango,datos_tomas):
    it=0
    for x in range(rango):   # Iteraciones Màximas
        plan={}
        contador=1
        ocupados=[]
        band=1
        actores=[1,2,3,4,5,6,7,8,9,10]
        numDia=[1,2,3,4,5]
        it=it+1
        while band==1:
                dia=[]
                itmax=0
                contarmax=0
                if len(ocupados)<30:
                    itmax,contarmax=tomas_aleatoria(ocupados, datos_tomas)
                else:
                    break
                dia.append(itmax+1)
                cruce=serie_tomas2(itmax,datos_tomas,ocupados)
                numDia=organizar_agenda(cruce,dia)
                for x in range(len(numDia)):
                    ocupados.append(numDia[x])
                if len(numDia) < 2:
                    break
                plan.setdefault(contador,numDia)
                contador=contador+1
        gsv=0
        # Imprimir resultado del Plan - Actores por dìa
        for y in plan:
                setRes={}
                setRes=set(setRes)
               # print('ACTORES DIA',y)
                for x in range(len(plan[y])):
                        sa=actores*datos_tomas.iloc[(plan[y][x])-1]
                        sa=np.array(list(sa))
                        sa=set(sa)
                        setRes=sa|setRes
                        contador=contador+1
                setRes.remove(0)
                gsv=gsv+ len(setRes)
        print('Total Gastos Servicios Doblajes: ',gsv)
        if gsv < 30:
            print('Plan: ',plan)
            print('Nº Iteraciones: ',it)
            break
    return

In [47]:
algoritmo_mejorado(500,df)

Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  29
Plan:  {1: [4, 3, 5, 11, 15, 1], 2: [2, 20, 6, 7, 12, 13], 3: [1, 22, 9, 25, 26, 27], 4: [27, 28, 29, 30, 8, 10], 5: [19, 14, 17, 18, 23, 24]}
Nº Iteraciones:  9

Este algoritmo busca ser una metaheuristica constructiva. Se parte de una solución vacía que se va iterando hasta encontrar una mejor. No puedo afirmar que es una solución optima, pero sí es una mejor que por fuerza bruta, siendo más precisa y eficiente.

(*)Calcula la complejidad del algoritmo
**Complejidad:** orden n**2

Respuesta

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [55]:
df_nuevos  = pd.read_excel('Datos_nuevos_doblajes.xlsx', header=None, skiprows=1)
df_nuevos.pop(11)
df_nuevos = np.array(df_nuevos)
df_nuevos = pd.DataFrame(df_nuevos, columns=['Toma','1','2','3','4','5','6','7','8','9','10','Total'])
df_nuevos= df_nuevos.drop(0,0)
df_nuevos= df_nuevos.drop(31,0)
df_nuevos= df_nuevos.drop(32,0)
df_nuevos= df_nuevos.drop(['Toma'],1)
df_nuevos= df_nuevos.drop(['Total'],1)
print('* Sesiones de Doblaje Tomas por Actores Nuevos Datos')
df_nuevos.index.name='Tomas / Actores'
display(df_nuevos)

* Sesiones de Doblaje Tomas por Actores Nuevos Datos

<ipython-input-55-5972ef29ce8c>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_nuevos= df_nuevos.drop(0,0)
<ipython-input-55-5972ef29ce8c>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_nuevos= df_nuevos.drop(31,0)
<ipython-input-55-5972ef29ce8c>:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_nuevos= df_nuevos.drop(32,0)
<ipython-input-55-5972ef29ce8c>:8: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_nuevos= df_nuevos.drop(['Toma'],1)
<ipython-input-55-5972ef29ce8c>:9: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_nuevos= df_nuevos.drop(['Total'],1)

                   1    2    3    4    5    6    7    8    9   10
Tomas / Actores
1                1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2                0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
3                0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
4                1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
5                0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6                1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
7                1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
8                1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
9                1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
10               1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
11               1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
12               1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0
13               1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
14               1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
15               1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
16               0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
17               1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
18               0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
19               1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
20               1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
21               0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
22               1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
23               1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
24               0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
25               1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
26               1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
27               0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
28               1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
29               1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
30               1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0

Aplica el algoritmo al juego de datos generado

In [56]:
algoritmo_mejorado(500,df_nuevos)

Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  31
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  42
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  31
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  41
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  41
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  31
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  31
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  32
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  40
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  35
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  39
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  34
Total Gastos Servicios Doblajes:  36
Total Gastos Servicios Doblajes:  37
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  33
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  38
Total Gastos Servicios Doblajes:  37

Respuesta

Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo


Respuesta:
#### Respuesta
- Proyecto fin de máster "Aplicación de algoritmos heurísticos para optimizar el coste de doblaje de películas"
- Autor: Alberto Caldas Lima
- Universidad Coruña, 4 Septiembre 2014

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta:

Considero que apostar por aproximaciones heuristicas puede seguir dando buenos resultados, sobre todo por su rama de algoritmos de busqueda y por ser un problema muy intuitivo sin mucho formalismo detrás. Sin embargo, creo que los algortimos geneticos podrían dar soluciones interesante. Intuitivamente, concibo las soluciones como una mutación de una solución base. Este punto de vista puede que funcione.